CREATE OR REPLACE TABLE HACKATHON.DATA.UNIFIED_DISTRICT_MONTHLY AS
WITH pop AS (
    SELECT
        DISTRICT_CODE,
        STANDARD_YEAR_MONTH,
        SUM(RESIDENTIAL_POPULATION) AS RESIDENTIAL_POPULATION,
        SUM(WORKING_POPULATION)     AS WORKING_POPULATION,
        SUM(VISITING_POPULATION)    AS VISITING_POPULATION,
        SUM(RESIDENTIAL_POPULATION + WORKING_POPULATION + VISITING_POPULATION) AS TOTAL_POPULATION
    FROM CONSUMPTION_ASSET.GRANDATA.FLOATING_POPULATION_INFO
    GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH
),
sales AS (
    SELECT
        DISTRICT_CODE,
        STANDARD_YEAR_MONTH,
        SUM(TOTAL_SALES)                    AS TOTAL_SALES,
        SUM(FOOD_SALES)                     AS FOOD_SALES,
        SUM(COFFEE_SALES)                   AS COFFEE_SALES,
        SUM(ENTERTAINMENT_SALES)            AS ENTERTAINMENT_SALES,
        SUM(DEPARTMENT_STORE_SALES)         AS DEPARTMENT_STORE_SALES,
        SUM(LARGE_DISCOUNT_STORE_SALES)     AS LARGE_DISCOUNT_STORE_SALES,
        SUM(SMALL_RETAIL_STORE_SALES)       AS SMALL_RETAIL_STORE_SALES,
        SUM(CLOTHING_ACCESSORIES_SALES)     AS CLOTHING_ACCESSORIES_SALES,
        SUM(SPORTS_CULTURE_LEISURE_SALES)   AS SPORTS_CULTURE_LEISURE_SALES,
        SUM(ACCOMMODATION_SALES)            AS ACCOMMODATION_SALES,
        SUM(TRAVEL_SALES)                   AS TRAVEL_SALES,
        SUM(BEAUTY_SALES)                   AS BEAUTY_SALES,
        SUM(HOME_LIFE_SERVICE_SALES)        AS HOME_LIFE_SERVICE_SALES,
        SUM(EDUCATION_ACADEMY_SALES)        AS EDUCATION_ACADEMY_SALES,
        SUM(MEDICAL_SALES)                  AS MEDICAL_SALES,
        SUM(ELECTRONICS_FURNITURE_SALES)    AS ELECTRONICS_FURNITURE_SALES,
        SUM(CAR_SALES)                      AS CAR_SALES,
        SUM(CAR_SERVICE_SUPPLIES_SALES)     AS CAR_SERVICE_SUPPLIES_SALES,
        SUM(GAS_STATION_SALES)              AS GAS_STATION_SALES,
        SUM(E_COMMERCE_SALES)               AS E_COMMERCE_SALES
    FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
    GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH
),
income AS (
    SELECT
        DISTRICT_CODE,
        STANDARD_YEAR_MONTH,
        AVG(MEDIAN_INCOME)                 AS MEDIAN_INCOME,
        ROUND(SUM(CUSTOMER_COUNT * MEDIAN_INCOME) / NULLIF(SUM(CUSTOMER_COUNT), 0) / 10)  AS WEIGHTED_MEDIAN_INCOME,
        AVG(AVERAGE_SCORE)                 AS AVERAGE_SCORE,
        AVG(AVERAGE_ASSET_AMOUNT)          AS AVERAGE_ASSET_AMOUNT,
        AVG(RATE_INCOME_UNDER_20M)         AS RATE_INCOME_UNDER_20M,
        AVG(RATE_INCOME_20M_TO_30M)        AS RATE_INCOME_20M_30M,
        AVG(RATE_INCOME_30M_TO_40M)        AS RATE_INCOME_30M_40M,
        AVG(RATE_INCOME_40M_TO_50M)        AS RATE_INCOME_40M_50M,
        AVG(RATE_INCOME_50M_TO_60M)        AS RATE_INCOME_50M_60M,
        AVG(RATE_INCOME_60M_TO_70M)        AS RATE_INCOME_60M_70M,
        AVG(RATE_INCOME_OVER_70M)          AS RATE_INCOME_OVER_70M,
        AVG(RATE_MODEL_GROUP_LARGE_COMPANY_EMPLOYEE)    AS RATE_MODEL_GROUP_LARGE_COMPANY_EMPLOYEE,
        AVG(RATE_MODEL_GROUP_GENERAL_EMPLOYEE)           AS RATE_MODEL_GROUP_GENERAL_EMPLOYEE,
        AVG(RATE_MODEL_GROUP_PROFESSIONAL_EMPLOYEE)      AS RATE_MODEL_GROUP_PROFESSIONAL_EMPLOYEE,
        AVG(RATE_MODEL_GROUP_EXECUTIVES)                 AS RATE_MODEL_GROUP_EXECUTIVES,
        AVG(RATE_MODEL_GROUP_GENERAL_SELF_EMPLOYED)      AS RATE_MODEL_GROUP_GENERAL_SELF_EMPLOYED,
        AVG(RATE_MODEL_GROUP_PROFESSIONAL_SELF_EMPLOYED) AS RATE_MODEL_GROUP_PROFESSIONAL_SELF_EMPLOYED,
        AVG(RATE_MODEL_GROUP_OTHERS)                     AS RATE_MODEL_GROUP_OTHERS
    FROM CONSUMPTION_ASSET.GRANDATA.ASSET_INCOME_INFO
    GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH
)
SELECT
    m.CITY_CODE,
    m.CITY_KOR_NAME,
    m.DISTRICT_CODE,
    m.DISTRICT_KOR_NAME,
    COALESCE(p.STANDARD_YEAR_MONTH, s.STANDARD_YEAR_MONTH, i.STANDARD_YEAR_MONTH) AS STANDARD_YEAR_MONTH,
    p.RESIDENTIAL_POPULATION,
    p.WORKING_POPULATION,
    p.VISITING_POPULATION,
    p.TOTAL_POPULATION,
    s.TOTAL_SALES,
    s.FOOD_SALES,
    s.COFFEE_SALES,
    s.ENTERTAINMENT_SALES,
    s.DEPARTMENT_STORE_SALES,
    s.LARGE_DISCOUNT_STORE_SALES,
    s.SMALL_RETAIL_STORE_SALES,
    s.CLOTHING_ACCESSORIES_SALES,
    s.SPORTS_CULTURE_LEISURE_SALES,
    s.ACCOMMODATION_SALES,
    s.TRAVEL_SALES,
    s.BEAUTY_SALES,
    s.HOME_LIFE_SERVICE_SALES,
    s.EDUCATION_ACADEMY_SALES,
    s.MEDICAL_SALES,
    s.ELECTRONICS_FURNITURE_SALES,
    s.CAR_SALES,
    s.CAR_SERVICE_SUPPLIES_SALES,
    s.GAS_STATION_SALES,
    s.E_COMMERCE_SALES,
    i.MEDIAN_INCOME,
    i.WEIGHTED_MEDIAN_INCOME,
    i.AVERAGE_SCORE,
    i.AVERAGE_ASSET_AMOUNT,
    i.RATE_INCOME_UNDER_20M,
    i.RATE_INCOME_20M_30M,
    i.RATE_INCOME_30M_40M,
    i.RATE_INCOME_40M_50M,
    i.RATE_INCOME_50M_60M,
    i.RATE_INCOME_60M_70M,
    i.RATE_INCOME_OVER_70M,
    i.RATE_MODEL_GROUP_LARGE_COMPANY_EMPLOYEE,
    i.RATE_MODEL_GROUP_GENERAL_EMPLOYEE,
    i.RATE_MODEL_GROUP_PROFESSIONAL_EMPLOYEE,
    i.RATE_MODEL_GROUP_EXECUTIVES,
    i.RATE_MODEL_GROUP_GENERAL_SELF_EMPLOYED,
    i.RATE_MODEL_GROUP_PROFESSIONAL_SELF_EMPLOYED,
    i.RATE_MODEL_GROUP_OTHERS
FROM CONSUMPTION_ASSET.GRANDATA.M_SCCO_MST m
LEFT JOIN pop p ON m.DISTRICT_CODE = p.DISTRICT_CODE
LEFT JOIN sales s ON m.DISTRICT_CODE = s.DISTRICT_CODE AND p.STANDARD_YEAR_MONTH = s.STANDARD_YEAR_MONTH
LEFT JOIN income i ON m.DISTRICT_CODE = i.DISTRICT_CODE AND p.STANDARD_YEAR_MONTH = i.STANDARD_YEAR_MONTH
WHERE COALESCE(p.STANDARD_YEAR_MONTH, s.STANDARD_YEAR_MONTH, i.STANDARD_YEAR_MONTH) IS NOT NULL