-- 1.Floating Population Aggregation

-- 1.1 city code & district code monthly summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_POPULATION_MONTHLY AS
SELECT
    PROVINCE_CODE,
    CITY_CODE,
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    SUM(RESIDENTIAL_POPULATION)                        AS TOTAL_RESIDENTIAL,
    SUM(WORKING_POPULATION)                            AS TOTAL_WORKING,
    SUM(VISITING_POPULATION)                           AS TOTAL_VISITING,
    SUM(RESIDENTIAL_POPULATION + WORKING_POPULATION + VISITING_POPULATION) AS TOTAL_POPULATION
FROM CONSUMPTION_ASSET.GRANDATA.FLOATING_POPULATION_INFO
GROUP BY PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH;

-- 1.2 Gender & age group summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_POPULATION_DEMO AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    SUM(RESIDENTIAL_POPULATION) AS RESIDENTIAL,
    SUM(WORKING_POPULATION)    AS WORKING,
    SUM(VISITING_POPULATION)   AS VISITING
FROM CONSUMPTION_ASSET.GRANDATA.FLOATING_POPULATION_INFO
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, GENDER, AGE_GROUP;

-- 1.3 Timeslot weekday_weekend summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_POPULATION_TIMESLOT AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    TIME_SLOT,
    WEEKDAY_WEEKEND,
    SUM(RESIDENTIAL_POPULATION) AS RESIDENTIAL,
    SUM(WORKING_POPULATION)    AS WORKING,
    SUM(VISITING_POPULATION)   AS VISITING
FROM CONSUMPTION_ASSET.GRANDATA.FLOATING_POPULATION_INFO
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, TIME_SLOT, WEEKDAY_WEEKEND;

-- 2 Card Sales Aggregation

-- 2.1 standary_year_month summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_MONTHLY AS
SELECT
    PROVINCE_CODE,
    CITY_CODE,
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    SUM(TOTAL_SALES)                    AS TOTAL_SALES,
    SUM(FOOD_SALES)                     AS FOOD_SALES,
    SUM(COFFEE_SALES)                   AS COFFEE_SALES,
    SUM(ENTERTAINMENT_SALES)            AS ENTERTAINMENT_SALES,
    SUM(DEPARTMENT_STORE_SALES)         AS DEPARTMENT_STORE_SALES,
    SUM(LARGE_DISCOUNT_STORE_SALES)     AS LARGE_DISCOUNT_STORE_SALES,
    SUM(SMALL_RETAIL_STORE_SALES)       AS SMALL_RETAIL_STORE_SALES,
    SUM(CLOTHING_ACCESSORIES_SALES)     AS CLOTHING_ACCESSORIES_SALES,
    SUM(SPORTS_CULTURE_LEISURE_SALES)   AS SPORTS_CULTURE_LEISURE_SALES,
    SUM(ACCOMMODATION_SALES)            AS ACCOMMODATION_SALES,
    SUM(TRAVEL_SALES)                   AS TRAVEL_SALES,
    SUM(BEAUTY_SALES)                   AS BEAUTY_SALES,
    SUM(HOME_LIFE_SERVICE_SALES)        AS HOME_LIFE_SERVICE_SALES,
    SUM(EDUCATION_ACADEMY_SALES)        AS EDUCATION_ACADEMY_SALES,
    SUM(MEDICAL_SALES)                  AS MEDICAL_SALES,
    SUM(ELECTRONICS_FURNITURE_SALES)    AS ELECTRONICS_FURNITURE_SALES,
    SUM(CAR_SALES)                      AS CAR_SALES,
    SUM(CAR_SERVICE_SUPPLIES_SALES)     AS CAR_SERVICE_SUPPLIES_SALES,
    SUM(GAS_STATION_SALES)              AS GAS_STATION_SALES,
    SUM(E_COMMERCE_SALES)               AS E_COMMERCE_SALES
FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
GROUP BY PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH;

-- 2.2 Weekday_weekend summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_WEEKDAY AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    WEEKDAY_WEEKEND,
    SUM(TOTAL_SALES)   AS TOTAL_SALES,
    SUM(FOOD_SALES)    AS FOOD_SALES,
    SUM(COFFEE_SALES)  AS COFFEE_SALES,
    SUM(ENTERTAINMENT_SALES)  AS ENTERTAINMENT_SALES,
    SUM(ACCOMMODATION_SALES)  AS ACCOMMODATION_SALES,
    SUM(BEAUTY_SALES)         AS BEAUTY_SALES,
    SUM(MEDICAL_SALES)        AS MEDICAL_SALES,
    SUM(E_COMMERCE_SALES)     AS E_COMMERCE_SALES
FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, WEEKDAY_WEEKEND;

-- 2.3 Lifestyle summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_LIFESTYLE AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    LIFESTYLE,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(FOOD_SALES)  AS FOOD_SALES,
    SUM(COFFEE_SALES) AS COFFEE_SALES,
    SUM(ENTERTAINMENT_SALES) AS ENTERTAINMENT_SALES,
    SUM(BEAUTY_SALES) AS BEAUTY_SALES
FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
WHERE LIFESTYLE IS NOT NULL AND LIFESTYLE != '*'
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, LIFESTYLE;

-- 2.4 Gender &age group summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_DEMO AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(FOOD_SALES)  AS FOOD_SALES,
    SUM(COFFEE_SALES) AS COFFEE_SALES,
    SUM(ENTERTAINMENT_SALES) AS ENTERTAINMENT_SALES,
    SUM(BEAUTY_SALES) AS BEAUTY_SALES
FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
WHERE AGE_GROUP != '*'
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, GENDER, AGE_GROUP;

-- 2.5 city average summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_CITY_AVG AS
SELECT
    m.CITY_CODE,
    c.STANDARD_YEAR_MONTH,
    AVG(c.TOTAL_SALES)                  AS AVG_TOTAL_SALES,
    AVG(c.FOOD_SALES)                   AS AVG_FOOD_SALES,
    AVG(c.COFFEE_SALES)                 AS AVG_COFFEE_SALES,
    AVG(c.ENTERTAINMENT_SALES)          AS AVG_ENTERTAINMENT_SALES,
    AVG(c.BEAUTY_SALES)                 AS AVG_BEAUTY_SALES,
    AVG(c.MEDICAL_SALES)                AS AVG_MEDICAL_SALES
FROM (
    SELECT DISTRICT_CODE, STANDARD_YEAR_MONTH,
           SUM(TOTAL_SALES) AS TOTAL_SALES,
           SUM(FOOD_SALES)  AS FOOD_SALES,
           SUM(COFFEE_SALES) AS COFFEE_SALES,
           SUM(ENTERTAINMENT_SALES) AS ENTERTAINMENT_SALES,
           SUM(BEAUTY_SALES) AS BEAUTY_SALES,
           SUM(MEDICAL_SALES) AS MEDICAL_SALES
    FROM CONSUMPTION_ASSET.GRANDATA.CARD_SALES_INFO
    GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH
) c
JOIN CONSUMPTION_ASSET.GRANDATA.M_SCCO_MST m
    ON c.DISTRICT_CODE = m.DISTRICT_CODE
GROUP BY m.CITY_CODE, c.STANDARD_YEAR_MONTH;


-- 3. Income & Asset Aggregation
-- 3.1 standary_year_month sumamry
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_INCOME_MONTHLY AS
SELECT
    PROVINCE_CODE,
    CITY_CODE,
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    AVG(AVERAGE_INCOME)           AS AVG_INCOME,
    AVG(MEDIAN_INCOME)            AS MEDIAN_INCOME,
    AVG(AVERAGE_HOUSEHOLD_INCOME) AS AVG_HOUSEHOLD_INCOME,
    AVG(AVERAGE_ASSET_AMOUNT)     AS AVG_ASSET,
    AVG(AVERAGE_SCORE)            AS AVG_CREDIT_SCORE,
    AVG(RATE_INCOME_UNDER_20M)    AS RATE_UNDER_20M,
    AVG(RATE_INCOME_20M_TO_30M)   AS RATE_20M_30M,
    AVG(RATE_INCOME_30M_TO_40M)   AS RATE_30M_40M,
    AVG(RATE_INCOME_40M_TO_50M)   AS RATE_40M_50M,
    AVG(RATE_INCOME_50M_TO_60M)   AS RATE_50M_60M,
    AVG(RATE_INCOME_60M_TO_70M)   AS RATE_60M_70M,
    AVG(RATE_INCOME_OVER_70M)     AS RATE_OVER_70M,
    AVG(RATE_MODEL_GROUP_LARGE_COMPANY_EMPLOYEE)      AS RATE_LARGE_COMPANY,
    AVG(RATE_MODEL_GROUP_GENERAL_EMPLOYEE)             AS RATE_GENERAL_EMPLOYEE,
    AVG(RATE_MODEL_GROUP_PROFESSIONAL_EMPLOYEE)        AS RATE_PROFESSIONAL,
    AVG(RATE_MODEL_GROUP_EXECUTIVES)                   AS RATE_EXECUTIVES,
    AVG(RATE_MODEL_GROUP_GENERAL_SELF_EMPLOYED)        AS RATE_GENERAL_SELF_EMPLOYED,
    AVG(RATE_MODEL_GROUP_PROFESSIONAL_SELF_EMPLOYED)   AS RATE_PROFESSIONAL_SELF_EMPLOYED,
    AVG(RATE_MODEL_GROUP_OTHERS)                       AS RATE_OTHERS
FROM CONSUMPTION_ASSET.GRANDATA.ASSET_INCOME_INFO
GROUP BY PROVINCE_CODE, CITY_CODE, DISTRICT_CODE, STANDARD_YEAR_MONTH;

-- 3.2 Gender & Age group summary
CREATE OR REPLACE TABLE CONSUMPTION_ASSET.GRANDATA.AGG_INCOME_DEMO AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    AVG(AVERAGE_INCOME)  AS AVG_INCOME,
    AVG(MEDIAN_INCOME)   AS MEDIAN_INCOME,
    AVG(AVERAGE_SCORE)   AS AVG_CREDIT_SCORE
FROM CONSUMPTION_ASSET.GRANDATA.ASSET_INCOME_INFO
GROUP BY DISTRICT_CODE, STANDARD_YEAR_MONTH, GENDER, AGE_GROUP;


-- 4. Unified Dashboard View
CREATE OR REPLACE VIEW CONSUMPTION_ASSET.GRANDATA.V_DISTRICT_SUMMARY AS
SELECT
    m.PROVINCE_CODE,
    m.PROVINCE_KOR_NAME,
    m.CITY_CODE,
    m.CITY_KOR_NAME,
    m.DISTRICT_CODE,
    m.DISTRICT_KOR_NAME,
    p.STANDARD_YEAR_MONTH,
    p.TOTAL_RESIDENTIAL,
    p.TOTAL_WORKING,
    p.TOTAL_VISITING,
    p.TOTAL_POPULATION,
    s.TOTAL_SALES,
    s.FOOD_SALES,
    s.COFFEE_SALES,
    s.ENTERTAINMENT_SALES,
    s.BEAUTY_SALES,
    s.MEDICAL_SALES,
    s.E_COMMERCE_SALES,
    i.AVG_INCOME,
    i.MEDIAN_INCOME,
    i.AVG_ASSET,
    i.AVG_CREDIT_SCORE
FROM CONSUMPTION_ASSET.GRANDATA.M_SCCO_MST m
LEFT JOIN CONSUMPTION_ASSET.GRANDATA.AGG_POPULATION_MONTHLY p
    ON m.DISTRICT_CODE = p.DISTRICT_CODE
LEFT JOIN CONSUMPTION_ASSET.GRANDATA.AGG_CARD_SALES_MONTHLY s
    ON m.DISTRICT_CODE = s.DISTRICT_CODE
    AND p.STANDARD_YEAR_MONTH = s.STANDARD_YEAR_MONTH
LEFT JOIN CONSUMPTION_ASSET.GRANDATA.AGG_INCOME_MONTHLY i
    ON m.DISTRICT_CODE = i.DISTRICT_CODE
    AND p.STANDARD_YEAR_MONTH = i.STANDARD_YEAR_MONTH;